/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 02:02:37 GMT 2024
 */

package com.williamfiset.algorithms.math;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.williamfiset.algorithms.math.CompressedPrimeSieve;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompressedPrimeSieve_ESTest extends CompressedPrimeSieve_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String string0 = "";
      stringArray0[0] = "";
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      int int0 = 6818;
      CompressedPrimeSieve.primeSieve(6818);
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      String[] stringArray1 = new String[5];
      stringArray1[0] = "";
      stringArray1[1] = "";
      stringArray1[2] = "";
      stringArray1[3] = "";
      stringArray1[4] = "";
      CompressedPrimeSieve.main(stringArray1);
      CompressedPrimeSieve.main(stringArray0);
      // Undeclared exception!
      CompressedPrimeSieve.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      long[] longArray0 = new long[3];
      longArray0[0] = 0L;
      longArray0[1] = (-1L);
      longArray0[2] = 823L;
      CompressedPrimeSieve.isPrime(longArray0, 7);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      long[] longArray0 = null;
      CompressedPrimeSieve.isPrime((long[]) null, 0);
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "%d is prime!\n";
      stringArray0[1] = ":(c?tx}9";
      stringArray0[2] = "";
      stringArray0[3] = "";
      CompressedPrimeSieve.main(stringArray0);
      String[] stringArray1 = new String[6];
      stringArray1[0] = "com.williamfiset.algorithms.math.CompressedPrimeSieve";
      stringArray1[1] = "P";
      stringArray1[2] = "z&(DRKY|FKK\"";
      stringArray1[3] = " ):y9li=l";
      stringArray1[4] = "";
      stringArray1[5] = "";
      CompressedPrimeSieve.main(stringArray1);
      int int0 = 833;
      // Undeclared exception!
      try { 
        CompressedPrimeSieve.isPrime((long[]) null, 833);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.CompressedPrimeSieve", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "e$bZ}:{G:<ZU4?";
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main((String[]) null);
      String[] stringArray1 = new String[1];
      stringArray1[0] = "6P2R`7|Coi_%Xv";
      CompressedPrimeSieve.main(stringArray1);
      String[] stringArray2 = new String[1];
      stringArray2[0] = "";
      CompressedPrimeSieve.main(stringArray2);
      String[] stringArray3 = new String[6];
      stringArray3[0] = "fuw";
      stringArray3[1] = "";
      stringArray3[2] = "V&i$7cpy]W#JTK.7dK";
      stringArray3[3] = "";
      stringArray3[4] = "4";
      stringArray3[5] = "";
      CompressedPrimeSieve.main(stringArray3);
      // Undeclared exception!
      try { 
        CompressedPrimeSieve.primeSieve((-1150));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.CompressedPrimeSieve", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = ":iJ";
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      int int0 = 2703;
      long[] longArray0 = CompressedPrimeSieve.primeSieve(2703);
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.main(stringArray0);
      String[] stringArray1 = new String[6];
      stringArray1[0] = ":iJ";
      stringArray1[1] = ":iJ";
      stringArray1[2] = ":iJ";
      stringArray1[3] = ":iJ";
      stringArray1[4] = ":iJ";
      stringArray1[5] = ":iJ";
      CompressedPrimeSieve.main(stringArray1);
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.isPrime(longArray0, 2703);
      CompressedPrimeSieve.main(stringArray0);
      CompressedPrimeSieve.primeSieve(1562);
      long[] longArray1 = CompressedPrimeSieve.primeSieve(1562);
      CompressedPrimeSieve.isPrime(longArray1, 1562);
      CompressedPrimeSieve.main(stringArray0);
      // Undeclared exception!
      CompressedPrimeSieve.primeSieve(1562);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "Q@7|Xr,y/";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "8.e";
      stringArray0[6] = "";
      stringArray0[7] = "";
      CompressedPrimeSieve.main(stringArray0);
      long[] longArray0 = new long[9];
      longArray0[0] = 1096L;
      longArray0[1] = 1L;
      longArray0[2] = 4456L;
      longArray0[3] = (-1L);
      longArray0[4] = (-2455L);
      longArray0[5] = 2427L;
      longArray0[6] = 1484L;
      longArray0[7] = 0L;
      longArray0[8] = 0L;
      // Undeclared exception!
      try { 
        CompressedPrimeSieve.isPrime(longArray0, 3135);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CompressedPrimeSieve.primeSieve(843);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "com.williamfiset.algorithms.math.CompressedPrimeSieve";
      stringArray0[1] = "";
      stringArray0[2] = "5[Zsifo~?o";
      stringArray0[3] = "com.williamfiset.algorithms.math.CompressedPrimeSieve";
      stringArray0[4] = "";
      stringArray0[5] = ")IEKPOQ";
      CompressedPrimeSieve.main(stringArray0);
      String[] stringArray1 = new String[3];
      stringArray1[0] = "j-";
      stringArray1[1] = ":VA";
      stringArray1[2] = "";
      CompressedPrimeSieve.main(stringArray1);
      // Undeclared exception!
      try { 
        CompressedPrimeSieve.primeSieve(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.williamfiset.algorithms.math.CompressedPrimeSieve", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CompressedPrimeSieve.main((String[]) null);
      CompressedPrimeSieve.main((String[]) null);
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      long[] longArray0 = new long[0];
      CompressedPrimeSieve.isPrime(longArray0, 0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CompressedPrimeSieve.primeSieve(1652);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CompressedPrimeSieve compressedPrimeSieve0 = new CompressedPrimeSieve();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "HG 3s<gv=pIQ<";
      stringArray0[1] = "HG 3s<gv=pIQ<";
      stringArray0[2] = "tS:-?d";
      CompressedPrimeSieve.main(stringArray0);
      String[] stringArray1 = new String[3];
      stringArray1[1] = "%d is prime!\n";
      stringArray1[2] = "!YIGv+e5<&`(Fo";
      CompressedPrimeSieve.main(stringArray1);
      CompressedPrimeSieve.main(stringArray0);
      // Undeclared exception!
      try { 
        CompressedPrimeSieve.primeSieve(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("com.williamfiset.algorithms.math.CompressedPrimeSieve", e);
      }
  }
}
