/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 01:56:22 GMT 2024
 */

package com.williamfiset.algorithms.math;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.williamfiset.algorithms.math.EulerTotientFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EulerTotientFunction_ESTest extends EulerTotientFunction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      Random.setNextRandom(329);
      // Undeclared exception!
      EulerTotientFunction.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EulerTotientFunction.eulersTotient(1357L);
      String[] stringArray0 = new String[0];
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.eulersTotient(1276L);
      EulerTotientFunction.eulersTotient(1899L);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.eulersTotient(1357L);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.eulersTotient(1357L);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.eulersTotient(1276L);
      EulerTotientFunction.eulersTotient(1276L);
      EulerTotientFunction.eulersTotient(1357L);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.eulersTotient(1357L);
      EulerTotientFunction.eulersTotient(1276L);
      EulerTotientFunction.main(stringArray0);
      EulerTotientFunction.main(stringArray0);
      // Undeclared exception!
      EulerTotientFunction.eulersTotient(1975L);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      EulerTotientFunction.eulersTotient(3091L);
      EulerTotientFunction.eulersTotient(365L);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        EulerTotientFunction.eulersTotient(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.EulerTotientFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      EulerTotientFunction.eulersTotient(1484L);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      // Undeclared exception!
      try { 
        EulerTotientFunction.eulersTotient((-3216L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.EulerTotientFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      EulerTotientFunction.eulersTotient(225L);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[0];
      EulerTotientFunction.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      // Undeclared exception!
      EulerTotientFunction.eulersTotient(5375L);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      EulerTotientFunction.eulersTotient(2L);
      EulerTotientFunction.eulersTotient(1271L);
      EulerTotientFunction.eulersTotient(1271L);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EulerTotientFunction eulerTotientFunction0 = new EulerTotientFunction();
      EulerTotientFunction.main((String[]) null);
      // Undeclared exception!
      try { 
        EulerTotientFunction.eulersTotient(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.EulerTotientFunction", e);
      }
  }
}
