/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 02:11:14 GMT 2024
 */

package com.williamfiset.algorithms.math;

import org.junit.Test;
import static org.junit.Assert.*;
import com.williamfiset.algorithms.math.GCD;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GCD_ESTest extends GCD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = GCD.gcd(0L, 0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = GCD.gcd((-1L), (-1L));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long long0 = GCD.gcd((-3366L), 0L);
      assertEquals(3366L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GCD.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GCD gCD0 = new GCD();
  }
}
