/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 01:58:37 GMT 2024
 */

package com.williamfiset.algorithms.math;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.williamfiset.algorithms.math.PrimeFactorization;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PrimeFactorization_ESTest extends PrimeFactorization_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      long long0 = 2750L;
      // Undeclared exception!
      PrimeFactorization.primeFactorization(2750L);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      PrimeFactorization.primeFactorization(2L);
      long long0 = (-2103L);
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization((-2103L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "9>K7y p";
      stringArray0[2] = ",6^b!8~]M 4O%  ";
      stringArray0[3] = "";
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      PrimeFactorization.primeFactorization(1L);
      long long0 = 0L;
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      long long0 = 0L;
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String string0 = "";
      stringArray0[0] = "";
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = null;
      // Undeclared exception!
      PrimeFactorization.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PrimeFactorization.primeFactorization(2060L);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "com.williamfiset.algorithms.math.PrimeFactorization";
      stringArray0[1] = "07'UnSUW";
      stringArray0[2] = "k";
      stringArray0[3] = "E%+arVHlzx";
      stringArray0[4] = "";
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = ",";
      stringArray0[3] = "kD$-F'?I]o";
      stringArray0[4] = "lv?[@o)h/97=m?K";
      stringArray0[5] = "";
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      PrimeFactorization.primeFactorization(2457L);
      long long0 = 0L;
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization(0L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization((-422L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      PrimeFactorization.primeFactorization(872342345L);
      // Undeclared exception!
      try { 
        PrimeFactorization.primeFactorization((-4267L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.williamfiset.algorithms.math.PrimeFactorization", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PrimeFactorization primeFactorization0 = new PrimeFactorization();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "wT";
      stringArray0[3] = "7*";
      // Undeclared exception!
      PrimeFactorization.main(stringArray0);
  }
}
