/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 29 02:12:10 GMT 2024
 */

package com.williamfiset.algorithms.math;

import org.junit.Test;
import static org.junit.Assert.*;
import com.williamfiset.algorithms.math.ExtendedEuclideanAlgorithm;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExtendedEuclideanAlgorithm_ESTest extends ExtendedEuclideanAlgorithm_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long[] longArray0 = ExtendedEuclideanAlgorithm.egcd(1722L, 1722L);
      assertArrayEquals(new long[] {1722L, 0L, 1L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long[] longArray0 = ExtendedEuclideanAlgorithm.egcd(0L, 0L);
      assertArrayEquals(new long[] {0L, 1L, 0L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      long[] longArray0 = ExtendedEuclideanAlgorithm.egcd((-1054L), (-348L));
      assertArrayEquals(new long[] {(-2L), 35L, (-106L)}, longArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExtendedEuclideanAlgorithm extendedEuclideanAlgorithm0 = new ExtendedEuclideanAlgorithm();
  }
}
